---
version: "3"
services:
  movies:
    image: areebahsan/moviesonpaytm:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  trains:
    image: areebahsan/trainsonpaytm:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: areebahsan/rechargeonpaytm:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  bills:
    image: areebahsan/billsonpaytm:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
